# Generated by Django 3.1.3 on 2020-11-21 02:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.TimeField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('meta_tag_description', models.TextField()),
            ],
        ),
    ]
