# Generated by Django 3.1.3 on 2020-11-21 03:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20201121_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='content_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
