# Generated by Django 3.1.3 on 2020-11-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20201121_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='meta_tag_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_tag_description_ru',
            field=models.TextField(null=True),
        ),
    ]
