# Generated by Django 3.1.3 on 2020-12-11 09:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20201121_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='content_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='content_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='content_fr',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_tag_description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_tag_description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_tag_description_fr',
            field=models.TextField(null=True),
        ),
    ]
