# Generated by Django 3.1.3 on 2020-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20201211_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='notification_class',
            field=models.CharField(choices=[('notification is-primary', 'notification is-primary'), ('notification is-link', 'notification is-link'), ('notification is-info', 'notification is-info'), ('notification is-success', 'notification is-success'), ('notification is-warning', 'notification is-warning'), ('notification is-danger', 'notification is-danger'), ('notification is-primary is-light', 'notification is-primary is-light'), ('notification is-link is-light', 'notification is-link is-light'), ('notification is-info is-light', 'notification is-info is-light'), ('notification is-success is-light', 'notification is-success is-light'), ('notification is-warning is-light', 'notification is-warning is-light'), ('notification is-danger is-light', 'notification is-danger is-light')], default='notification is-primary', max_length=40),
        ),
    ]
