# Generated by Django 3.1.3 on 2020-12-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label_text',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Отображение в админке On/Of'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Отображение в админке On/Of'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fifth_label_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Label_Text5', to='catalog.label_text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_label_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Label_Text1', to='catalog.label_text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fourth_label_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Label_Text4', to='catalog.label_text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_label_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Label_Text2', to='catalog.label_text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_label_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Label_Text3', to='catalog.label_text'),
        ),
    ]
