# Generated by Django 3.1.3 on 2020-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201202_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label_text',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Не отображать в админке On/Of'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Не отображать в админке On/Of'),
        ),
    ]
