# Generated by Django 3.1.3 on 2020-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201202_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label_text',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='label_text',
            name='admin_name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя которое не переводится и отображается только в админке'),
        ),
    ]
