# Generated by Django 3.1.3 on 2020-12-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201202_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label_text',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='label_text',
            name='name_ru',
        ),
    ]
