# Generated by Django 3.1.3 on 2020-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201202_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label_text',
            name='admin_name',
        ),
        migrations.AddField(
            model_name='label_text',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='label_text',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='label_text',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='label_text',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='label_text',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
