# Generated by Django 3.1.3 on 2020-12-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20201202_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Label_Text',
            new_name='LabelText',
        ),
    ]
