# Generated by Django 3.1.3 on 2020-12-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201203_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=160, verbose_name='Meta Tag Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_de',
            field=models.TextField(blank=True, default=None, max_length=160, null=True, verbose_name='Meta Tag Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default=None, max_length=160, null=True, verbose_name='Meta Tag Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, default=None, max_length=160, null=True, verbose_name='Meta Tag Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, default=None, max_length=160, null=True, verbose_name='Meta Tag Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default=None, max_length=160, null=True, verbose_name='Meta Tag Description'),
        ),
    ]
