# Generated by Django 3.1.3 on 2020-12-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20201205_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='option_select_percent',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='option_select_percent_price',
            field=models.IntegerField(default=0, verbose_name='На сколько процентов увеличиваем итого'),
        ),
    ]
