# Generated by Django 3.1.3 on 2021-01-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20201214_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_system_settings',
            name='domain',
            field=models.CharField(blank=True, help_text='Your current domain: unitpay.money or unitpay.ru', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment_system_settings',
            name='projectId',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_system_settings',
            name='publicId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_system_settings',
            name='secretKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
