# Generated by Django 3.1.3 on 2021-01-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210112_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSelect3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admin_name', models.CharField(default='', max_length=50, verbose_name='Имя виджета админке формата Product.admin_name_OptionSelect3.name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='required_select_3',
            field=models.BooleanField(default=False, verbose_name='Обязательная или нет поле Select 3'),
        ),
        migrations.CreateModel(
            name='OptionSelect3Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('option_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.optionselect3')),
                ('option_select_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.optionselectelement')),
            ],
        ),
        migrations.AddField(
            model_name='optionselect3',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='option_check_box_element_3', through='catalog.OptionSelect3Summary', to='catalog.OptionSelectElement'),
        ),
    ]
