# Generated by Django 3.1.3 on 2021-01-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210117_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_select_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.optionselect3'),
        ),
    ]
