# Generated by Django 3.1.3 on 2021-01-23 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0026_auto_20210123_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='user_driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
    ]
