# Generated by Django 3.1.3 on 2021-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20210123_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markup_coefficient_after_200_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.65, max_digits=8, null=True, verbose_name='Коэффициент наценки платформы если цена больше 200 евро'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_coefficient_before_15_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.65, max_digits=8, null=True, verbose_name='Коэффициент наценки платформы если цена меньше 15 евро'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_coefficient_before_200_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.65, max_digits=8, null=True, verbose_name='Коэффициент наценки платформы если цена меньше 200 евро,но больше 15'),
        ),
        migrations.AddField(
            model_name='product',
            name='need_specific_markup_coefficient',
            field=models.BooleanField(default=False, verbose_name='Нужно ли использовать специфические коэффициенты прибыли для данного продукта'),
        ),
    ]
