# Generated by Django 3.1.3 on 2021-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20210123_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='markup_coefficient',
            field=models.DecimalField(decimal_places=2, default=0.65, max_digits=8, verbose_name='Коэффициент наценки платформы для текущего ордера, заполняется автоматически'),
        ),
    ]
