# Generated by Django 3.1.3 on 2021-01-23 20:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_order_markup_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_value_private',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Значение приватных элементов label продукта'),
        ),
    ]
