# Generated by Django 3.1.3 on 2021-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_order_label_value_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fifth_label_is_private',
            field=models.BooleanField(default=False, verbose_name='Является ли значение приватной информацией'),
        ),
        migrations.AddField(
            model_name='product',
            name='first_label_is_private',
            field=models.BooleanField(default=False, verbose_name='Является ли значение приватной информацией'),
        ),
        migrations.AddField(
            model_name='product',
            name='fourth_label_is_private',
            field=models.BooleanField(default=False, verbose_name='Является ли значение приватной информацией'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_label_is_private',
            field=models.BooleanField(default=False, verbose_name='Является ли значение приватной информацией'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_label_is_private',
            field=models.BooleanField(default=False, verbose_name='Является ли значение приватной информацией'),
        ),
    ]
