# Generated by Django 3.1.3 on 2021-01-23 21:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20210123_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label_value',
            field=tinymce.models.HTMLField(default='', verbose_name='Значение элементов label продукта'),
        ),
    ]
