# Generated by Django 3.1.3 on 2021-01-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20210123_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
