# Generated by Django 3.1.3 on 2021-01-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20210124_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_skype',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_telegram',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
