# Generated by Django 3.1.3 on 2021-01-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_driver_driver_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available_for_new_driver',
            field=models.BooleanField(default=False),
        ),
    ]
