# Generated by Django 3.1.3 on 2021-01-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_order_available_for_new_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='available_for_new_driver',
        ),
        migrations.AddField(
            model_name='order',
            name='driver_rank',
            field=models.CharField(default='Verified', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='driver_rank',
            field=models.CharField(choices=[('New', 'New'), ('Verified', 'Verified')], default='Verified', max_length=40),
        ),
    ]
