# Generated by Django 3.1.3 on 2021-01-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20210124_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='driver_rank',
        ),
    ]
